[target.aarch64-linux-android]
ar = "E:/Library/android_sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar.exe"
linker = "E:/Library/android_sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android24-clang.cmd"

[env]
AR_aarch64_linux_android = "E:/Library/android_sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar.exe"
CC_aarch64_linux_android = "E:/Library/android_sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe"
CFLAGS_aarch64_linux_android = "--target=aarch64-linux-android24 --sysroot=E:/Library/android_sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/windows-x86_64/sysroot -fPIC"
CXX_aarch64_linux_android = "E:/Library/android_sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe"
CXXFLAGS_aarch64_linux_android = "--target=aarch64-linux-android24 --sysroot=E:/Library/android_sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/windows-x86_64/sysroot -fPIC"
RANLIB_aarch64_linux_android = "E:/Library/android_sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ranlib.exe"
PERL = "D:/Scoop/apps/msys2/current/usr/bin/perl.exe"
MAKE = "D:/Scoop/apps/msys2/current/usr/bin/make.exe"
